### ISSUE TITLE
В мастере не работают force short и force long

### ISSUE THREAD

**Issue by s9gf4ult** [axce1/tomacco#12]
В контекстном меню пиктограмки в трее.

**Comment by axce1** [comment]
done

**Comment by s9gf4ult** [comment]
Все еще не работает long
1. Стартуешь помидор
2. Останавливаешь
3. force long

```
Traceback (most recent call last):
  File "main.py", line 244, in long_tray
    self.on_btn_lpause()
  File "main.py", line 69, in on_btn_lpause
    self.fms.next_state(state.LongEvent(), time.time())
  File "/home/razor/tmp/tomacco/state.py", line 90, in next_state
    self.state = LongEvent(stime)
TypeError: object() takes no parameters
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by axce1** [comment]
fix
